### ISSUE TITLE
"Unknown command: 'search_index'" While provisioning using devstack OPENEDX_RELEASE=koa

### ISSUE THREAD

**Issue by asadali145** [edx/edx-notes-api#249]
I have checked the requirements of notes for koa and I am not able to the django-elasticsearch-dsl in it. I am getting an error while provisioning using devstack koa. 

**Unknown command: 'search_index'. Did you mean clear_index?**

`docker-compose exec edx_notes_api bash -c 'source /edx/app/$1/$1_env && cd /edx/app/$1/$1/ && python manage.py search_index --rebuild -f' -- edx_notes_api`

The above line generates this and breaks the provision, For now I have changed it to use the _rebuild_index_ of haystack.

**Comment by asadali145** [comment]
This needs to be fixed in devstack I guess. Can't find a place to report this.

**Comment by nedbat** [comment]
Can you post about it on https://discuss.openedx.org, and provide more details, like how you are using devstack with Koa? Thanks.
